[package]
name = "array_from_scratch"
version = "0.1.0"
authors = ["Kim Jeker <git@kije.ch>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
